- name: installed docker
  hosts: all
  become: true

  tasks:

  - name: Ensure pip3 is present
    apt:
      update_cache: yes
      name: python3-pip
      state: present

  - name: Ensure requests is present
    become: true
    pip:
      name: requests
      executable: pip3

  - name: Ensure docker-py is present
    become: true
    pip:
      name: docker-py
      state: present

  - name: Ensure docker is present
    apt:
      name: docker.io
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started
  
- name: building
  hosts: bild
  become: true   
  
  tasks:
  - name: copy dockerfile
    copy:
      src: /var/lib/jenkins/certification_work_0824/dockerfile
      dest: /home/user

  - name: docker build 
    become: true
    docker_image:
      path: /home/user
      name: prob1
      tag: latest
  
  - name: tag image in repo
    become: true
    docker_image:
      name: prob1
      tag: latest
      repository: cr.yandex/{{ myrepo }}/prob1
      push: yes

- name: run in prod
  hosts: prod
  become: true

  tasks:
  - name: pull image
    become: true
    docker_image:
      name: cr.yandex/{{ myrepo }}/prob1
      tag: latest

  - name: Run 
    become: true
    docker_container:
      name: prod
      image: cr.yandex/{{ myrepo }}/prob1
      state: started
      ports:
        - "8080:8080"