#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: user
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICAp7cHJUBf4Nk/cJoUX7e5m6Hch7As/tfmT9Xnzh2Sc sverre\sverre@Sverre
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+xw0+r1uOy79CCr3uaon7IgjR3qAc14ZlZ6DEgBS7DHezdaUIQTCZWoe4RcHMhRi2B6Jb/BpaOpFOVFIDx0L5BcFcBB6z+xzVjhGFurUKIdWrOo+Wr6+RasLiRaSAhs34GebAOKVq/ikH6tob7oPDnaGIxcSTR5TmPofZbVUg/MuZ6pdB2MWPZ/ogoaLaNv7bFIKSOFbA+lbFzZLBDtSO/tFHkOY8D/1755jIVIQD9U/0+kgQ3Z1OE+m/WY8MtV8Y9SXWdmQ8MgntEwhU7IyvkZHJFEmVqpg0etbuANwbTnGUV44CQlmoyG90qAE93OpkijmfVKZxE7RLjw60xH2FG89EAP4hQZ4Ds6Jcpqvaf1+Y04k7Pa4k14Hg/7EzYmLpSQ0/zaPiv4wLInmXA7vxM4IfsethiR+unOJ2nmDEy7Omq38q0MldRN3LQyulekGMMdCBZcyaQ81MJY9Us8/FKq3v5gVyPvZsha87hy4qpwmn1MSx4PPCSgqmDdtxBt8= jenkins@teraform